### ISSUE TITLE
`any_of` should accept a list of `ArrayExpression`s

### ISSUE THREAD

**Issue by sneakers-the-rat** [linkml/linkml-model#199]
In translating NWB, I am replacing my ArrayLike class array representations with the linkml array spec. NWB models support a `dims` and `shape` list of list expression such that a given dataset can have several different possible shapes: https://schema-language.readthedocs.io/en/stable/specification_language_description.html#dims

Given the implementation of `array` at a slot level rather than a type, I need to be able to use it in `any_of` like this:

```yaml
classes:
  MyClass:
    attributes:
      name: my_array
      range: integer
      any_of:
      - array:
          dimensions:
          - alias: x
            exact_cardinality: 3
      - array:
          dimensions:
          - alias: x
            exact_cardinality: 3
          - alias: y
            exact_cardinality: 4
```

this, of course, opens up the potential for combinatorics between `any_of` used with `range` and `array` like this:

```yaml
any_of:
- range: integer
- range: float
- array:
    dimensions:
    - alias: x
      exact_cardinality: 3
- array:
    dimensions:
    - alias: x
      exact_cardinality: 3
    - alias: y
      exact_cardinality: 4
```

which I would interpret as meaning the product:

- NDArray[Shape['3'], int]
- NDArray[Shape['3, 4'], int]
- NDArray[Shape['3'], float]
- NDArray[Shape['3, 4'], float]

and like this:

```yaml
any_of:
- range: integer
  array:
    dimensions:
    - alias: x
      exact_cardinality: 3
- range: float
  array:
    dimensions:
    - alias: x
      exact_cardinality: 3
    - alias: y
      exact_cardinality: 4
```

which would be (unambiguously)

- NDArray[Shape['3'], int]
- NDArray[Shape['3, 4'], float]

and i actually think that's a good thing - if we refactor the generators like https://github.com/linkml/linkml/pull/2019, separating the different phases of the build and using build results objects, then it would be easy to handle the combinatorics there (and i would implement it). It doesn't explode the complexity of arrays, it would just require better iteration in the generators (which is good anyway). 

without this change, I don't think there would be a way to express a slot being able to have multiple exactly parameterized/labeled array shapes. 

cc @rly
